'use client'
import Head from 'next/head'
import CustomTextField from 'src/components/text-field'
import UserLayoutNoApp from 'src/views/layouts/UserLayoutNoApp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Hello world! 1111</h1>
      <CustomTextField id='outlined-basic' label='Outlined' variant='outlined' />
    </>
  )
}

Home.guestGuard = false
Home.authGuard = false
Home.getLayout = (page: React.ReactElement) => <UserLayoutNoApp>{page}</UserLayoutNoApp>
